[2025-07-02T10:44:08.584+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_model_training.check_new_data scheduled__2025-07-01T00:00:00+00:00 [queued]>
[2025-07-02T10:44:08.594+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_model_training.check_new_data scheduled__2025-07-01T00:00:00+00:00 [queued]>
[2025-07-02T10:44:08.594+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-02T10:44:08.608+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): check_new_data> on 2025-07-01 00:00:00+00:00
[2025-07-02T10:44:08.616+0000] {standard_task_runner.py:60} INFO - Started process 313 to run task
[2025-07-02T10:44:08.618+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'transport_model_training', 'check_new_data', 'scheduled__2025-07-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/train_model_dag.py', '--cfg-path', '/tmp/tmpx_n5mcqa']
[2025-07-02T10:44:08.620+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask check_new_data
[2025-07-02T10:44:08.676+0000] {task_command.py:423} INFO - Running <TaskInstance: transport_model_training.check_new_data scheduled__2025-07-01T00:00:00+00:00 [running]> on host c9653bbec911
[2025-07-02T10:44:08.777+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hamdanialhassangandi2020@gmail.com' AIRFLOW_CTX_DAG_OWNER='ml_team' AIRFLOW_CTX_DAG_ID='transport_model_training' AIRFLOW_CTX_TASK_ID='check_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T00:00:00+00:00'
[2025-07-02T10:44:08.794+0000] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2025-07-02T10:44:08.796+0000] {filesystem.py:66} INFO - Poking for file /home/lusitech/AmaliTech/ML_Transport_Accra/data/raw/new_data_flag.txt
[2025-07-02T10:49:08.901+0000] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2025-07-02T10:49:08.902+0000] {filesystem.py:66} INFO - Poking for file /home/lusitech/AmaliTech/ML_Transport_Accra/data/raw/new_data_flag.txt
[2025-07-02T10:54:09.013+0000] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2025-07-02T10:54:09.014+0000] {filesystem.py:66} INFO - Poking for file /home/lusitech/AmaliTech/ML_Transport_Accra/data/raw/new_data_flag.txt
[2025-07-02T10:55:07.706+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-02T10:55:07.709+0000] {process_utils.py:131} INFO - Sending 15 to group 313. PIDs of all processes in the group: [313]
[2025-07-02T10:55:07.722+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 313
[2025-07-02T10:55:07.722+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-02T10:55:07.750+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-07-02T10:55:07.755+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=transport_model_training, task_id=check_new_data, execution_date=20250701T000000, start_date=20250702T104408, end_date=20250702T105507
[2025-07-02T10:55:07.781+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task check_new_data (Task received SIGTERM signal; 313)
[2025-07-02T10:55:07.825+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=313, status='terminated', exitcode=1, started='10:44:08') (313) terminated with exit code 1
[2025-07-02T10:55:07.826+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-07-02T10:55:07.880+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
