[2025-07-03T07:39:45.267+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_model_training.train_model scheduled__2025-07-02T00:00:00+00:00 [queued]>
[2025-07-03T07:39:45.274+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_model_training.train_model scheduled__2025-07-02T00:00:00+00:00 [queued]>
[2025-07-03T07:39:45.275+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-03T07:39:45.290+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2025-07-02 00:00:00+00:00
[2025-07-03T07:39:45.296+0000] {standard_task_runner.py:60} INFO - Started process 313 to run task
[2025-07-03T07:39:45.298+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'transport_model_training', 'train_model', 'scheduled__2025-07-02T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/train_model_dag.py', '--cfg-path', '/tmp/tmpgrplmerr']
[2025-07-03T07:39:45.300+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask train_model
[2025-07-03T07:39:45.349+0000] {task_command.py:423} INFO - Running <TaskInstance: transport_model_training.train_model scheduled__2025-07-02T00:00:00+00:00 [running]> on host 42cda6469fc7
[2025-07-03T07:39:45.423+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hamdanialhassangandi2020@gmail.com' AIRFLOW_CTX_DAG_OWNER='ml_team' AIRFLOW_CTX_DAG_ID='transport_model_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-02T00:00:00+00:00'
[2025-07-03T07:39:45.424+0000] {train_model_dag.py:74} INFO - Running training command: python /opt/***/scripts/train.py --config /opt/***/configs/config.yaml
[2025-07-03T07:39:48.623+0000] {train_model_dag.py:79} ERROR - Training failed: Traceback (most recent call last):
  File "/opt/***/scripts/train.py", line 12, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

[2025-07-03T07:39:48.624+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_model_dag.py", line 75, in train
    result = subprocess.run(cmd, capture_output=True, text=True, check=True, cwd=str(PROJECT_ROOT))
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/scripts/train.py', '--config', '/opt/airflow/configs/config.yaml']' returned non-zero exit status 1.
[2025-07-03T07:39:48.636+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=transport_model_training, task_id=train_model, execution_date=20250702T000000, start_date=20250703T073945, end_date=20250703T073948
[2025-07-03T07:39:48.648+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task train_model (Command '['python', '/opt/airflow/scripts/train.py', '--config', '/opt/airflow/configs/config.yaml']' returned non-zero exit status 1.; 313)
[2025-07-03T07:39:48.692+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-03T07:39:48.718+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-03T09:57:05.489+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_model_training.train_model scheduled__2025-07-02T00:00:00+00:00 [queued]>
[2025-07-03T09:57:05.507+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_model_training.train_model scheduled__2025-07-02T00:00:00+00:00 [queued]>
[2025-07-03T09:57:05.508+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-03T09:57:05.533+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2025-07-02 00:00:00+00:00
[2025-07-03T09:57:05.546+0000] {standard_task_runner.py:60} INFO - Started process 230 to run task
[2025-07-03T09:57:05.551+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'transport_model_training', 'train_model', 'scheduled__2025-07-02T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/train_model_dag.py', '--cfg-path', '/tmp/tmpj6whc7pq']
[2025-07-03T09:57:05.554+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask train_model
[2025-07-03T09:57:05.648+0000] {task_command.py:423} INFO - Running <TaskInstance: transport_model_training.train_model scheduled__2025-07-02T00:00:00+00:00 [running]> on host 298f3b2e4b4c
[2025-07-03T09:57:05.777+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hamdanialhassangandi2020@gmail.com' AIRFLOW_CTX_DAG_OWNER='ml_team' AIRFLOW_CTX_DAG_ID='transport_model_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-02T00:00:00+00:00'
[2025-07-03T09:57:05.778+0000] {train_model_dag.py:74} INFO - Running training command: python /opt/***/scripts/train.py --config /opt/***/configs/config.yaml
[2025-07-03T09:57:08.774+0000] {train_model_dag.py:79} ERROR - Training failed: Traceback (most recent call last):
  File "/opt/***/scripts/train.py", line 12, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

[2025-07-03T09:57:08.776+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_model_dag.py", line 75, in train
    result = subprocess.run(cmd, capture_output=True, text=True, check=True, cwd=str(PROJECT_ROOT))
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/scripts/train.py', '--config', '/opt/airflow/configs/config.yaml']' returned non-zero exit status 1.
[2025-07-03T09:57:08.789+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=transport_model_training, task_id=train_model, execution_date=20250702T000000, start_date=20250703T095705, end_date=20250703T095708
[2025-07-03T09:57:08.806+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task train_model (Command '['python', '/opt/airflow/scripts/train.py', '--config', '/opt/airflow/configs/config.yaml']' returned non-zero exit status 1.; 230)
[2025-07-03T09:57:08.824+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-03T09:57:08.855+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
