[2025-07-02T11:46:19.907+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_model_training.check_new_data manual__2025-07-02T11:46:18.943047+00:00 [queued]>
[2025-07-02T11:46:19.915+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_model_training.check_new_data manual__2025-07-02T11:46:18.943047+00:00 [queued]>
[2025-07-02T11:46:19.916+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-02T11:46:19.928+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): check_new_data> on 2025-07-02 11:46:18.943047+00:00
[2025-07-02T11:46:19.933+0000] {standard_task_runner.py:60} INFO - Started process 1291 to run task
[2025-07-02T11:46:19.935+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'transport_model_training', 'check_new_data', 'manual__2025-07-02T11:46:18.943047+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/train_model_dag.py', '--cfg-path', '/tmp/tmpx95sdf4y']
[2025-07-02T11:46:19.937+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask check_new_data
[2025-07-02T11:46:19.982+0000] {task_command.py:423} INFO - Running <TaskInstance: transport_model_training.check_new_data manual__2025-07-02T11:46:18.943047+00:00 [running]> on host 41d3a1b16a2e
[2025-07-02T11:46:20.072+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hamdanialhassangandi2020@gmail.com' AIRFLOW_CTX_DAG_OWNER='ml_team' AIRFLOW_CTX_DAG_ID='transport_model_training' AIRFLOW_CTX_TASK_ID='check_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T11:46:18.943047+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-02T11:46:18.943047+00:00'
[2025-07-02T11:46:20.094+0000] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2025-07-02T11:46:20.096+0000] {filesystem.py:66} INFO - Poking for file /opt/***/data/raw/new_data_flag.txt
[2025-07-02T11:51:20.204+0000] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2025-07-02T11:51:20.205+0000] {filesystem.py:66} INFO - Poking for file /opt/***/data/raw/new_data_flag.txt
[2025-07-02T11:55:30.960+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-02T11:55:30.970+0000] {process_utils.py:131} INFO - Sending 15 to group 1291. PIDs of all processes in the group: [1291]
[2025-07-02T11:55:30.970+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1291
[2025-07-02T11:55:30.971+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-02T11:55:30.993+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-07-02T11:55:30.999+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=transport_model_training, task_id=check_new_data, execution_date=20250702T114618, start_date=20250702T114619, end_date=20250702T115530
[2025-07-02T11:55:31.036+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task check_new_data (Task received SIGTERM signal; 1291)
[2025-07-02T11:55:31.064+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1291, status='terminated', exitcode=1, started='11:46:19') (1291) terminated with exit code 1
[2025-07-02T11:55:31.066+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-07-02T11:55:31.142+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
